[package]
name = "mina_ws_client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.15"
futures-util = "0.3"
url = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
