[package]
name = "avax_ws_client"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonrpsee = { version = "0.14", features = ["ws-client"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
serde_json = "1.0"